// AUTO-GENERATED by scripts/themes/import.ts — do not edit by hand.
// 导入主题的汇总入口。手写主题在 ../themes.ts 与 ../themes-extra.ts。

import type { Theme } from '../theme-kit'
import { XIAOHU_THEMES } from './xiaohu'
import { RAPHAEL_THEMES } from './raphael'
import { HUASHENG_THEMES } from './huasheng'
import { MD_WECHAT_THEMES } from './md-wechat'
import { WENYAN_THEMES } from './wenyan'
import { XEDIT_THEMES } from './xedit'
import { INKPRESS_THEMES } from './inkpress'

export const IMPORTED_THEMES: Theme[] = [
  ...XIAOHU_THEMES,
  ...RAPHAEL_THEMES,
  ...HUASHENG_THEMES,
  ...MD_WECHAT_THEMES,
  ...WENYAN_THEMES,
  ...XEDIT_THEMES,
  ...INKPRESS_THEMES,
]
