// 生成主题包的落盘逻辑。
// 产物是提交进仓库的 TS：importer 只在开发机跑，运行时不依赖任何上游仓库。

import fs from 'node:fs'
import path from 'node:path'
import type { ImportedThemeSpec } from '../../../src/lib/theme-kit'

export interface GeneratedPack {
  /** 文件名与导出名前缀，例如 xiaohu → src/lib/themes-imported/xiaohu.ts */
  id: string
  /** 上游仓库，写进文件头注释 */
  repo: string
  license: string
  themes: ImportedThemeSpec[]
}

// importer 由 esbuild 打包到 node_modules/.tmp 后再跑，import.meta.dirname 会指向打包产物，
// 所以输出目录按 cwd 解析——npm 脚本一律在 app/ 下执行。
const OUT_DIR = path.resolve(process.cwd(), 'src/lib/themes-imported')

/** JSON 字面量：字符串保持可读，其余交给 JSON.stringify 保证转义正确。 */
function lit(value: unknown, indent: string): string {
  return JSON.stringify(value, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : indent + line))
    .join('\n')
}

function emitSpec(spec: ImportedThemeSpec, indent: string): string {
  const o = spec.meta.origin
  const originLines = [
    `${indent}  origin: {`,
    `${indent}    kind: ${JSON.stringify(o.kind)},`,
    `${indent}    project: ${JSON.stringify(o.project)},`,
    `${indent}    author: ${JSON.stringify(o.author)},`,
    `${indent}    repo: ${JSON.stringify(o.repo)},`,
    `${indent}    license: ${JSON.stringify(o.license)},`,
    o.licenseFile ? `${indent}    licenseFile: ${JSON.stringify(o.licenseFile)},` : null,
    `${indent}    attribution: ${JSON.stringify(o.attribution)},`,
    o.upstream ? `${indent}    upstream: ${JSON.stringify(o.upstream)},` : null,
    o.adapted ? `${indent}    adapted: ${JSON.stringify(o.adapted)},` : null,
    `${indent}  },`,
  ].filter(Boolean) as string[]

  return [
    `${indent}{`,
    `${indent}  id: ${JSON.stringify(spec.id)},`,
    `${indent}  name: ${JSON.stringify(spec.name)},`,
    `${indent}  desc: ${JSON.stringify(spec.desc)},`,
    `${indent}  category: ${JSON.stringify(spec.category)},`,
    `${indent}  meta: {`,
    `${indent}    styles: ${JSON.stringify(spec.meta.styles)},`,
    `${indent}    complexity: ${spec.meta.complexity},`,
    `${indent}    color: ${JSON.stringify(spec.meta.color)},`,
    ...originLines,
    `${indent}  },`,
    `${indent}  palette: ${lit(spec.palette, indent + '  ')},`,
    `${indent}  styles: ${lit(spec.styles, indent + '  ')},`,
    `${indent}}`,
  ].join('\n')
}

export function writePack(pack: GeneratedPack): string {
  fs.mkdirSync(OUT_DIR, { recursive: true })
  const constName = `${pack.id.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()}_THEMES`
  const body = [
    `// AUTO-GENERATED by scripts/themes/import.ts — do not edit by hand.`,
    `// Source: ${pack.repo} (${pack.license}).`,
    `// 每套主题的原始出处见 meta.origin.upstream；许可证文本见 meta.origin.licenseFile。`,
    ``,
    `import { buildTheme, type ImportedThemeSpec } from '../theme-kit'`,
    ``,
    `const SPECS: ImportedThemeSpec[] = [`,
    pack.themes.map((t) => emitSpec(t, '  ')).join(',\n'),
    `]`,
    ``,
    `export const ${constName} = SPECS.map(buildTheme)`,
    ``,
  ].join('\n')
  const file = path.join(OUT_DIR, `${pack.id}.ts`)
  fs.writeFileSync(file, body, 'utf8')
  return file
}

export function writeIndex(packs: GeneratedPack[]): string {
  fs.mkdirSync(OUT_DIR, { recursive: true })
  const lines = [
    `// AUTO-GENERATED by scripts/themes/import.ts — do not edit by hand.`,
    `// 导入主题的汇总入口。手写主题在 ../themes.ts 与 ../themes-extra.ts。`,
    ``,
    `import type { Theme } from '../theme-kit'`,
  ]
  for (const p of packs) {
    const constName = `${p.id.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()}_THEMES`
    lines.push(`import { ${constName} } from './${p.id}'`)
  }
  lines.push('')
  lines.push('export const IMPORTED_THEMES: Theme[] = [')
  for (const p of packs) {
    const constName = `${p.id.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()}_THEMES`
    lines.push(`  ...${constName},`)
  }
  lines.push(']')
  lines.push('')
  const file = path.join(OUT_DIR, 'index.ts')
  fs.writeFileSync(file, lines.join('\n'), 'utf8')
  return file
}
